version: 0.1.1
commit: 'chore: bump to v%.%.%'
files:
  README.md:
    - deps_info v%.%.%
    - 'https://deno.land/x/deps_info@v%.%.%/mod.ts'
    - 'https://deno.land/x/deps_info@v%.%.%/cli.ts'
  cli.ts: v%.%.%
